### ISSUE TITLE
Quote style not preserved for dependencies modification

### ISSUE THREAD

**Issue by jpsingleton** [adamchainz/django-linear-migrations#57]
After running `rebase-migration` against a migration that uses double quotes `"` the updated `dependencies` tuple list uses single quotes `'`.

**Comment by adamchainz** [comment]
This is a result of using `ast.dump` and out of scope for django-linear-migrations to try change.

On projects using pre-commit to run black, run `pre-commit` after `./manage.py rebase-migration` to have it apply. pre-commit doesn't run on rebase commits due to a limitation in git: https://github.com/pre-commit/pre-commit/issues/1696
